### ISSUE TITLE
python mutator module issue

### ISSUE THREAD

**Issue by XingweiLin** [vanhauser-thc/AFLplusplus#135]
Hi, 

I want to use python mutator module, I have installed `python2.7-dev`, and use `make source-only` to build afl. But when I invoke afl with `AFL_PYTHON_MODULE="python_mutators.example" PYTHONPATH=. ./afl-fuzz ...`, it reported that `Your AFL binary was built without Python support`. It seems the Makefile cannot detect python2.7.

Then I installed `python3.7-dev`, and build afl with `make source-only`. Then run the afl-fuzz with python module, But it reported that:
```
[!] WARNING: Could not check CPU scaling governor
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
AttributeError: module 'python_mutators.example' has no attribute 'trim'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
AttributeError: module 'python_mutators.example' has no attribute 'trim'
[!] WARNING: Python module does not implement trim API, standard trimming will be used.
```

python3.7 doesn't have apt_pkg module.

Any idea to use python mutator module in afl++?

**Comment by andreafioraldi** [comment]
Try with `sudo apt-get install --reinstall python3-apt`

**Comment by andreafioraldi** [comment]
@vanhauser-thc we should define `trim` in the example.

**Comment by XingweiLin** [comment]
> Try with `sudo apt-get install --reinstall python3-apt`

emm, this doesn't make effect. still the error

**Comment by andreafioraldi** [comment]
Got the same error on Ubuntu 18.04 but it seems to not affect the fuzzer, it works, the error is only ugly.

**Comment by andreafioraldi** [comment]
btw this is Marc realm, he recently ported the python mutator to py3, wait for him

**Comment by XingweiLin** [comment]
Is there any way for me to choose the python version? Can I choose python2.7 to build and use the python mutator module? It seems the my python3.7 destroy my python environment.

**Comment by andreafioraldi** [comment]
@vanhauser-thc look at this. After this fix and the unicorn merge IMO we can do a new release.

**Comment by vanhauser-thc** [comment]
@XingweiLin 
this will take a few back and forth messages I guess.

Can you please do a "make clean" and past here the output of "make"? (not make distrib or anything else please). Please update your git state before you do.

**Comment by XingweiLin** [comment]
@vanhauser-thc 
```
# /AFLplusplus on git:master x [9:06:09]
$ git pull
Already up to date.

# /AFLplusplus on git:master x [9:06:13]
$ make
[*] Checking for the default compiler cc...
[*] Checking for the ability to compile x86 code...
[+] shmat seems to be working.
[+] Python 3.7m support seems to be working.
[+] Everything seems to be working, ready to compile.
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -I include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -Wno-unused-function src/afl-gcc.c -o afl-gcc -ldl
set -e; for i in afl-g++ afl-clang afl-clang++; do ln -sf afl-gcc $i; done
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -I include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -Wno-unused-function -c src/afl-common.c -o src/afl-common.o
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -I include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -Wno-unused-function -c src/afl-sharedmem.c -o src/afl-sharedmem.o
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -I include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -Wno-unused-function -c src/afl-forkserver.c -o src/afl-forkserver.o
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -I include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -Wno-unused-function src/afl-fuzz-misc.c src/afl-fuzz-globals.c src/afl-fuzz-extras.c src/afl-fuzz-queue.c src/afl-fuzz-one.c src/afl-fuzz-python.c src/afl-fuzz-stats.c src/afl-fuzz-init.c src/afl-fuzz.c src/afl-fuzz-bitmap.c src/afl-fuzz-run.c src/afl-common.o src/afl-sharedmem.o src/afl-forkserver.o -o afl-fuzz -DUSE_PYTHON -I-I/usr/include/python3.7m -I/usr/include/python3.7m -ldl -L/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu -L/usr/lib -lpython3.7m -lcrypt -lpthread -ldl  -lutil -lm  -ldl
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -I include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -Wno-unused-function src/afl-showmap.c src/afl-common.o src/afl-sharedmem.o -o afl-showmap -ldl
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -I include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -Wno-unused-function src/afl-tmin.c src/afl-common.o src/afl-sharedmem.o src/afl-forkserver.o -o afl-tmin -ldl
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -I include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -Wno-unused-function src/afl-gotcpu.c -o afl-gotcpu -ldl
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -I include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -Wno-unused-function src/afl-analyze.c src/afl-common.o src/afl-sharedmem.o -o afl-analyze -ldl
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -I include/ -DAFL_PATH=\"/usr/local/lib/afl\" -DBIN_PATH=\"/usr/local/bin\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -Wno-unused-function src/afl-as.c -o afl-as -ldl
ln -sf afl-as as
[*] Testing the CC wrapper and instrumentation output...
./afl-showmap -m none -q -o .test-instr0 ./test-instr < /dev/null
echo 1 | ./afl-showmap -m none -q -o .test-instr1 ./test-instr
[+] All right, the instrumentation seems to be working!
[+] LLVM users: see llvm_mode/README.llvm for a faster alternative to afl-gcc.
[+] All done! Be sure to review the README.md - it's pretty short and useful.
NOTE: If you can read this, your terminal probably uses white background.
This will make the UI hard to read. See docs/status_screen.txt for advice.
```

**Comment by XingweiLin** [comment]
actually, I fixed this issue by `sudo cp apt_pkg.cpython-36m-x86_64-linux-gnu.so apt_pkg.cpython-37m-x86_64-linux-gnu.so` in `/usr/lib/python3/dist-packages` dir.

seems python3.7-dev lacks this library.

**Comment by vanhauser-thc** [comment]
can you please try this:

dpkg -S `find / -name "apt_pkg.cpython-36m*.so"`
(or if this fails the dpkg -S /path/to/that/library/you/copied output)

I would like to know which package provides that library.

**Comment by andreafioraldi** [comment]
Maybe we should also do a list of exact dependencies for the modern distributions that build packages with afl++

**Comment by XingweiLin** [comment]
> can you please try this:
> 
> dpkg -S `find / -name "apt_pkg.cpython-36m*.so"`
> (or if this fails the dpkg -S /path/to/that/library/you/copied output)
> 
> I would like to know which package provides that library.

```
$ dpkg -S /usr/lib/python3/dist-packages/apt_pkg.cpython-36m-x86_64-linux-gnu.so
python3-apt: /usr/lib/python3/dist-packages/apt_pkg.cpython-36m-x86_64-linux-gnu.so
```

**Comment by vanhauser-thc** [comment]
thanks!

**Comment by XingweiLin** [comment]
sorry, but I don't why this issue was closed.
The issue hasn't been fixed.
The `python3-apt` package doesn't make help to this issue.

**Comment by vanhauser-thc** [comment]
it was closed because its an issue in Ubuntu packaging. sorry for not stating that. I updated the documentation to say to also install python3-apt, but thats all that we can do.

or do you think its different?

**Comment by XingweiLin** [comment]
Yeah, it's an issue in Ubuntu packaging. Maybe you can add the solution I used to fix this issue to the documentation. not sure if that's appropriate.
thank you for your reply.

**Comment by vanhauser-thc** [comment]
I think the right approach is to make a bug report at Ubuntu? or maybe its in a different package for python3.7?

The workaround is a bad idea as its mixing 3.6 with 3.7 so be happy if its working for you :)

**Comment by andreafioraldi** [comment]
Ubuntu launchpad is not the best place for bug reports. It will be slow, I have even unanswered security bugs reports. Do it but also add the workaround in the readme.
