### ISSUE TITLE
Unicorn tests fail on Raspberry Pi 4

### ISSUE THREAD

**Issue by hexcoder-** [vanhauser-thc/AFLplusplus#157]
On my Raspberry Pi 4  (4GB) running Raspbian 32-Bit, I tried to run tests with unicorn_mode.
Building unicorn_mode proceeded without error, but testing failed
```
[*] Testing: unicorn_mode                                                                                                                                                                   
[*] Using python binary /usr/bin/python                                                                                                                                                     
[*] running afl-fuzz for unicorn_mode, this will take approx 25 seconds                                                                                                                     
CUT------------------------------------------------------------------CUT                                                                                                                    
[*] Spinning up the fork server...                                                                                                                                                            
[+] All right - fork server is up.                                                                                                                                                            
afl-fuzz++2.59d based on afl by Michal Zalewski and a big online community                                                                                                                  
[+] afl++ is maintained by Marc "van Hauser" Heuse, Heiko "hexcoder" Eissfeldt and Andrea Fioraldi                                                                                            
[+] afl++ is open source, get it at https://github.com/vanhauser-thc/AFLplusplus                                                                                                              
[+] Power schedules from github.com/mboehme/aflfast                                                                                                                                           
[+] Python Mutator and llvm_mode whitelisting from github.com/choller/afl                                                                                                                     
[+] afl-tmin fork server patch from github.com/nccgroup/TriforceAFL                                                                                                                           
[+] MOpt Mutator from github.com/puppet-meteor/MOpt-AFL                                                                                                                                       
[*] Getting to work...                                                                                                                                                                        
[+] Using exploration-based constant power schedule (EXPLORE)                                                                                                                                 
[+] Looks like we're not running on a tty, so I'll be a bit less verbose.                                                                                                                     
[+] You have 4 CPU cores and 1 runnable tasks (utilization: 25%).                                                                                                                             
[+] Try parallel jobs - see docs/parallel_fuzzing.txt.                                                                                                                                        
[*] Checking CPU core loadout...                                                                                                                                                              
[+] Found a free CPU core, binding to #0.                                                                                                                                                     
[*] Checking core_pattern...                                                                                                                                                                  
[*] Setting up output directories...                                                                                                                                                          
[*] Scanning 'in'...                                                                                                                                                                          
[+] No auto-generated dictionary tokens to reuse.                                                                                                                                             
[*] Creating hard links for all input files...                                                                                                                                                
[*] Validating target binary...                                                                                                                                                               
[*] Attempting dry run with 'id:000000,time:0,orig:in'...                                                                                                                                     

[-] Oops, the program crashed with one of the test cases provided. There are                                                                                                                  
    several possible explanations:                                                                                                                                                            

    - The test case causes known crashes under normal working conditions. If                                                                                                                  
      so, please remove it. The fuzzer should be seeded with interesting                                                                                                                      
      inputs - but not ones that cause an outright crash.                                                                                                                                     

    - The current memory limit (200 MB) is too low for this program, causing                                                                                                                  
      it to die due to OOM when parsing valid files. To fix this, try                                                                                                                         
      bumping it up with the -m setting in the command line. If in doubt,                                                                                                                     
      try something along the lines of:                                                                                                                                                       

      ( ulimit -Sd $[199 << 10]; /path/to/binary [...] <testcase )                                                                                                                            

      Tip: you can use http://jwilk.net/software/recidivm to quickly                                                                                                                          
      estimate the required amount of virtual memory for the binary. Also,                                                                                                                    
      if you are using ASAN, see docs/notes_for_asan.txt.                                                                                                                                     

    - Least likely, there is a horrible bug in the fuzzer. If other options                                                                                                                   
      fail, poke <afl-users@googlegroups.com> for troubleshooting tips.                                                                                                                       

[-] PROGRAM ABORT : Test case 'id:000000,time:0,orig:in' results in a crash                                                                                                                 
         Location : perform_dry_run(), src/afl-fuzz-init.c:603                                                                                                                              

CUT------------------------------------------------------------------CUT                                                                                                                      
[!] afl-fuzz is not working correctly with unicorn_mode
```

I assume this should work (since unicorn does support ARM).
Thanks!

**Comment by andreafioraldi** [comment]
@hexcoder- can you use AFL_DEBUG_CHILD_OUTPUT ?

**Comment by domenukk** [comment]
I should have a pi laying around somewhere, I'll try to reproduce this in a bit

**Comment by hexcoder-** [comment]
@andreafioraldi Sure, will do after work.

**Comment by hexcoder-** [comment]
Hmm, no additional output with AFL_DEBUG_CHILD_OUTPUT=1...

**Comment by hexcoder-** [comment]
I am hoping for Dominik to take over...

**Comment by hexcoder-** [comment]
Now I am sure, that python2 is used for building unicornafl and also for running the test. A manual `import unicornafl` in python from `which python` succeeded. So it is something else...

**Comment by domenukk** [comment]
Thanks for checking. I'll try it out on my own pi asap :)

**Comment by andreafioraldi** [comment]
showmap works?

**Comment by hexcoder-** [comment]
Ah, I could now manually run simple_test_harness.py
```
pi@raspberrypi:~/AFLplusplus/test $ python ../unicorn_mode/samples/simple/simple_test_harness.py in/in
Loading data input from in/in
Speicherzugriffsfehler
```
`Speicherzugriffsfehler` is German for `Segmentation violation`.

File in/in contains "0\n".

That should help debugging, i hope. A stack trace would have been nice though.
It seems to be non portable python code.

**Comment by andreafioraldi** [comment]
valgrind?

**Comment by hexcoder-** [comment]
From running with gdb:
```
Program received signal SIGSEGV, Segmentation fault.
0xb5a76e0c in helper_wait_mips () from /home/pi/.cache/Python-Eggs/unicornafl-1.0.2rc1-py2.7.egg-tmp/unicornafl/lib/libunicornafl.so
(gdb) bt
#0  0xb5a76e0c in helper_wait_mips () from /home/pi/.cache/Python-Eggs/unicornafl-1.0.2rc1-py2.7.egg-tmp/unicornafl/lib/libunicornafl.so
#1  0xb4cbc6fc in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) q

```

**Comment by andreafioraldi** [comment]
This is very strange. helper_wait is the routine that simply trigger an hlt execption to the virtual cpu. @domenukk , is vanilla unicorn working with arm hosts?

**Comment by domenukk** [comment]
Playing around with it right now. Updating my pi first. Btw a simple `make` of aflpp on ARM fails as it the "compiler can't generate x86 code." - is there a branch for the Pi?

**Comment by andreafioraldi** [comment]
It should not fail, just report that you're not on x86

**Comment by hexcoder-** [comment]
Yeah, you need to set AFL_NO_X86=1...

**Comment by hexcoder-** [comment]
I agree.

**Comment by domenukk** [comment]
Unicorn fails without our AFL additions on ARM, too. I've opened an issue upstream.
https://github.com/unicorn-engine/unicorn/issues/1183


btw. `AFL_NO_X86=1` should probably always be set when arch != x86(64)?

**Comment by vanhauser-thc** [comment]
> btw. `AFL_NO_X86=1` should probably always be set when arch != x86(64)?

makes sense IMHO. as I test in the lto branch at the moment I put it there for testing

**Comment by hexcoder-** [comment]
One more problem with the tests is that on raspberry pi not only the test for `afl-gcc` is skipped, but also those for `afl-showmap`, `afl-cmin`, `afl-tmin`, (which are not dependent on intel cpus).

So I try to rearrange those...

**Comment by hexcoder-** [comment]
Automatic AFL_NO_X86 setting and afl-cmin/afl-tmin tests are in.

**Comment by hexcoder-** [comment]
Automatic AFL_NO_X86 setting and afl-cmin/afl-tmin tests are in.

**Comment by SmailCatLog** [comment]
https://github.com/unicorn-engine/unicorn/issues/1203#issue-562135253

retry it

**Comment by hexcoder-** [comment]
Easier said than done.

@domenukk: How do you test the proposed fix (which is not committed yet)? There is only `build_unicorn_support.sh` which destroys my patched tcg.c when cloning to unicornafl.

Some time ago there was a tool called `make` invented. I would like to use that, so that

1. patch tcg.c
2. make
3. make tests

would just work.

**Comment by hexcoder-** [comment]
ok, once i managed to outtrick `build_unicorn_support.sh`, I got it compiled with the proposed fix, and it tests ok (that is unicorn_mode and unicorn_mode compcov test cases were ok now).

So thanks! Now upstream should commit the fix.

**Comment by domenukk** [comment]
I can open a pr for unicorn unless @SmailCatLog you want to do it. Thanks for the fix! :) 
Thanks for testing  @hexcoder, my pi died earlier when I worked on it.

**Comment by SmailCatLog** [comment]
> open a pr for unicorn

Please you open a pr for unicorn.

**Comment by domenukk** [comment]
The pr is here https://github.com/unicorn-engine/unicorn/pull/1205
It's already commited to the unicornafl repo, @hexcoder in case you still have your pi around, maybe double check it's working now so this issue can be closed :)

**Comment by hexcoder-** [comment]
Yes, Raspberry Pi 4 and x86 both now work with unicorn tests. Closing the issue...
