### ISSUE TITLE
libdislocator stalls in OpenBSD

### ISSUE THREAD

**Issue by hexcoder-** [vanhauser-thc/AFLplusplus#70]
While porting our new test script `test/test.sh` to OpenBSD, I saw that the test for libdislocator (detecting a memory corruption) simply stalls and needs to be Ctrl-C'ed.
The lib is used with LD_PRELOAD=...

The reason is unknown yet.

**Comment by devnexen** [comment]
There might be an additional option in OpenBSD case, not using libdislocator here but playing with [MALLOC_OPTIONS](https://man.openbsd.org/free.3#MALLOC_OPTIONS). Hope it is useful !

**Comment by hexcoder-** [comment]
Thanks, I will check it out.

**Comment by hexcoder-** [comment]
I started the test case `test/test-compcov.c` with the debugger and got this:
```
obsd$ gdb --args ./test-compcov BUFFEROVERFLOW 
GNU gdb 6.3
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-unknown-openbsd6.5"...
(gdb) set environment LD_PRELOAD=../libdislocator.so
(gdb) b __dislocator_alloc
Function "__dislocator_alloc" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (__dislocator_alloc) pending.
(gdb) r
Starting program: /home/heiko/AFLplusplus/test/test-compcov BUFFEROVERFLOW
Breakpoint 2 at 0x102a14983cd: file libdislocator.so.c, line 104.
Pending breakpoint "__dislocator_alloc" resolved

Breakpoint 2, __dislocator_alloc (len=16) at libdislocator.so.c:104
104	  if (total_mem + len > max_mem || total_mem + len < total_mem) {
Current language:  auto; currently minimal
(gdb) n

Breakpoint 2, __dislocator_alloc (len=24) at libdislocator.so.c:104
104	  if (total_mem + len > max_mem || total_mem + len < total_mem) {
(gdb) 
^C
Program received signal SIGINT, Interrupt.
sched_yield () at -:3
3	-: No such file or directory.
	in -
Current language:  auto; currently asm
(gdb) bt
#0  sched_yield () at -:3
#1  0x00000101db2b9f75 in _libc__spinlock (lock=Variable "lock" is not available.
) at /usr/src/lib/libc/thread/rthread.c:50
#2  0x00000101db277e43 in _rthread_mutex_timedlock (mutexp=0x102a149c018, trywait=0, abs=0x0, timed=0) at /usr/src/lib/libc/thread/rthread_mutex.c:154
#3  0x00000101db304b99 in pthread_once (once_control=0x102a149c010, init_routine=0x102a1498e30 <emutls_init>) at /usr/src/lib/libc/thread/rthread_once.c:24
#4  0x00000102a1498c9d in __emutls_get_address (control=0x102a149a030) at /usr/src/lib/libcompiler_rt/emutls.c:116
#5  0x00000102a14983d9 in __dislocator_alloc (len=24) at libdislocator.so.c:104
#6  0x00000102a14982b4 in calloc (elem_len=1, elem_cnt=24) at libdislocator.so.c:178
#7  0x00000101db277e58 in _rthread_mutex_timedlock (mutexp=0x102a149c018, trywait=0, abs=0x0, timed=0) at /usr/src/lib/libc/thread/rthread_mutex.c:53
#8  0x00000101db304b99 in pthread_once (once_control=0x102a149c010, init_routine=0x102a1498e30 <emutls_init>) at /usr/src/lib/libc/thread/rthread_once.c:24
#9  0x00000102a1498c9d in __emutls_get_address (control=0x102a149a030) at /usr/src/lib/libcompiler_rt/emutls.c:116
#10 0x00000102a14983d9 in __dislocator_alloc (len=16) at libdislocator.so.c:104
#11 0x00000102a14986bf in malloc (len=16) at libdislocator.so.c:195
#12 0x000000ffbc5ba3fe in main (argc=2, argv=0x7f7ffffd5958) at test-compcov.c:20
(gdb) 
```
This is Ubuntu 18.10 running VirtualBox running OpenBSD 6.5.

Here is the relevant function from libdislocator:
```
/* This is the main alloc function. It allocates one page more than necessary,
   sets that tailing page to PROT_NONE, and then increments the return address
   so that it is right-aligned to that boundary. Since it always uses mmap(),
   the returned memory will be zeroed. */

static void* __dislocator_alloc(size_t len) {

  void* ret;

  if (total_mem + len > max_mem || total_mem + len < total_mem) {

    if (hard_fail) FATAL("total allocs exceed %u MB", max_mem / 1024 / 1024);

    DEBUGF("total allocs exceed %u MB, returning NULL", max_mem / 1024 / 1024);

    return NULL;

  }

  /* We will also store buffer length and a canary below the actual buffer, so
     let's add 8 bytes for that. */

  ret = mmap(NULL, (1 + PG_COUNT(len + 8)) * PAGE_SIZE, PROT_READ | PROT_WRITE,
             MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);

  if (ret == (void*)-1) {

    if (hard_fail) FATAL("mmap() failed on alloc (OOM?)");

    DEBUGF("mmap() failed on alloc (OOM?)");

    return NULL;

  }

  /* Set PROT_NONE on the last page. */

  if (mprotect(ret + PG_COUNT(len + 8) * PAGE_SIZE, PAGE_SIZE, PROT_NONE))
    FATAL("mprotect() failed when allocating memory");

  /* Offset the return pointer so that it's right-aligned to the page
     boundary. */

  ret += PAGE_SIZE * PG_COUNT(len + 8) - len - 8;

  /* Store allocation metadata. */

  ret += 8;

  PTR_L(ret) = len;
  PTR_C(ret) = ALLOC_CANARY;

  total_mem += len;

  return ret;

}

```
It seems there is some recursion through mmap() which results in
infinite locking in libc.

**Comment by devnexen** [comment]
I was not able to pinpoint to mmap (even disabling all still blocks at the same line) however the program segfault if I change to let s volatile those variables. Seems the TLS is the issue but might be wrong.

**Comment by hexcoder-** [comment]
Crummy workaround for the stall with the latest commit a282ae22afec0e5d5a8455c7aaa3e472839788e4. It is the allocation of thread local storage for these variables:
```
static __thread size_t total_mem;       /* Currently allocated mem          */

static __thread u32 call_depth;         /* To avoid recursion via fprintf() */

```
I put these lines before
```
#ifdef  __OpenBSD__
#define __thread
#warning no thread support available
#endif
```
and now they don't live in thread local storage (thus no thread support), but the stall is gone.
